feat: Add Code Coverage

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -9,7 +9,12 @@ on:
         type: string
         default: "./"
       add-editorconfig:
-        description: "Condition for whether the editorconfig gets added"
+        description: "Condition for whether the .editorconfig gets added"
+        required: false
+        type: boolean
+        default: true
+      add-runsettings:
+        description: "Condition for whether the .runsettings gets added"
         required: false
         type: boolean
         default: true
@@ -24,6 +29,11 @@ on:
         type: boolean
         default: true
       add-analyzers:
+        description: "Condition for whether analyzers gets verified that they are added"
+        required: false
+        type: boolean
+        default: true
+      add-dependencies:
         description: "Condition for whether analyzers gets verified that they are added"
         required: false
         type: boolean
@@ -44,6 +54,9 @@ on:
 
 jobs:
   build-and-test:
+    permissions:
+      pull-requests: write
+      contents: read
     defaults:
       run:
         working-directory: ${{ inputs.working-directory }}
@@ -73,7 +86,7 @@ jobs:
         run: cp temp/Shared/.editorconfig ${{ inputs.working-directory }}
       - name: Copy .runsettings file
         working-directory: "."
-        if: ${{ inputs.add-editorconfig }}
+        if: ${{ inputs.add-runsettings }}
         run: cp temp/Shared/.runsettings ${{ inputs.working-directory }}
 
       - name: Restore dependencies
@@ -107,6 +120,34 @@ jobs:
           Set-Location -Path ${{ github.workspace }}
           }
 
+      # Check for certain dependencies
+      - name: Check if dependent packages are installed and add if not
+        if: ${{ inputs.add-dependencies }}
+        working-directory: "."
+        shell: pwsh
+        run: |
+          $analyzersPath = "${{ github.workspace }}/temp/Shared/dependencies.txt"
+          if (-not (Test-Path -Path $analyzersPath)) {
+          Write-Error "File not found: $analyzersPath"
+          exit 1
+          }
+          $testDirectories = Get-ChildItem -Path "${{ inputs.working-directory }}" -Filter "*Tests" -Directory
+          if ($testDirectories.Count -eq 0) {
+            Write-Error "No directories with '*Tests' found in '${{ inputs.working-directory }}'"
+            exit 1
+          }
+          $testDirectories | ForEach-Object {
+          Set-Location -Path $_.FullName
+          $analyzers = Get-Content $analyzersPath
+          foreach ($analyzer in $analyzers) {
+              $package = dotnet list package | Select-String -Pattern $analyzer
+              if ($null -eq $package) {
+              dotnet add package $analyzer
+              }
+          }
+          Set-Location -Path ${{ github.workspace }}
+          }
+
       - name: Run dotnet format
         if: ${{ inputs.check-formatting }}
         run: dotnet format --verify-no-changes --verbosity diagnostic
@@ -114,4 +155,23 @@ jobs:
       - name: Build
         run: dotnet build --no-restore -p:Nullable=${{ inputs.enable-nullability == true && 'enable' || 'disable' }} -p:TreatWarningsAsErrors=true -p:EnableNETAnalyzers=${{ inputs.enable-net-analyzers }} -p:CodeAnalysisTreatWarningsAsErrors=true -p:NoWarn=EnableGenerateDocumentationFile -p:AnalysisLevel=latest-Recommended -p:EnforceCodeStyleInBuild=${{ inputs.dotnet-build-enforce-code-style }}
       - name: Test
-        run: dotnet test --no-build --verbosity normal
+        run: dotnet test --no-build --verbosity normal --settings ${{github.workspace}}/.runsettings /p:CollectCoverage=true --collect:"XPlat Code Coverage" --logger trx --results-directory coveragereport
+
+      - name: ReportGenerator
+        id: reportgenerator
+        if: github.event_name == 'pull_request'
+        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
+        with:
+          reports: '**/coverage.cobertura.xml'
+          targetdir: coveragereport
+          reporttypes: MarkdownSummaryGithub
+
+      - name: Post comment to PR
+        if: github.event_name == 'pull_request'
+        uses: marocchino/sticky-pull-request-comment@v2
+        with:
+          recreate: true
+          path: coveragereport/SummaryGithub.md
+
+      - name: Write to Job Summary
+        run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
